### ISSUE TITLE
Required Parameters are not documented

### ISSUE THREAD

**Issue by spuder** [Webtrends/kafka#6]
If you attempt to setup with test kitchen, you will get an error "ERROR: Node attributes are read-only when you do not specify which precedence level to set."

You must specify [:kafka][:broker_id] in attributes/default.rb to work around it. 

```
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-ubuntu-1204>
       Starting Chef Client, version 12.0.3
       Compiling Cookbooks...

       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cookbooks/ND-Kafka/recipes/default.rb
       ================================================================================

       Chef::Exceptions::ImmutableAttributeModification
       ------------------------------------------------
       Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cookbooks/kafka/recipes/default.rb:30:in `from_file'
         /tmp/kitchen/cookbooks/ND-Kafka/recipes/default.rb:12:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cookbooks/kafka/recipes/default.rb:

        23:
        24:  java_home   = node['java']['java_home']
        25:
        26:  user = node[:kafka][:user]
        27:  group = node[:kafka][:group]
        28:
        29:  if node[:kafka][:broker_id].nil? || node[:kafka][:broker_id].empty?
        30>>     node[:kafka][:broker_id] = node[:ipaddress].gsub(".","")
        31:  end
        32:
        33:  if node[:kafka][:broker_host_name].nil? || node[:kafka][:broker_host_name].empty?
        34:      node[:kafka][:broker_host_name] = node[:fqdn]
        35:  end
        36:
        37:  log "Broker id: #{node[:kafka][:broker_id]}"
        38:  log "Broker name: #{node[:kafka][:broker_host_name]}"
        39:


       Running handlers:

       Running handlers complete


       Chef Client failed. 0 resources updated in 1.083742411 seconds
       [2015-02-02T23:03:42+00:00] ERROR: Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'
       [2015-02-02T23:03:42+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <default-ubuntu-1204>.
>>>>>> Please see .kitchen/logs/default-ubuntu-1204.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '
sudo -E /opt/chef/bin/chef-solo --config /tmp/kitchen/solo.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json
']
```

**Comment by ustuehler** [comment]
Same as issue #7.
