### ISSUE TITLE
Fails to set broker_id

### ISSUE THREAD

**Issue by spuder** [Webtrends/kafka#7]
This cookbook fails to setup the broker_id

Setup

``` bash
      ================================================================================
       Recipe Compile Error in /tmp/kitchen/cookbooks/ND-Kafka/recipes/default.rb
       ================================================================================

       Chef::Exceptions::ImmutableAttributeModification
       ------------------------------------------------
       Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cookbooks/kafka/recipes/default.rb:30:in `from_file'
         /tmp/kitchen/cookbooks/ND-Kafka/recipes/default.rb:12:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cookbooks/kafka/recipes/default.rb:

        23:
        24:  java_home   = node['java']['java_home']
        25:
        26:  user = node[:kafka][:user]
        27:  group = node[:kafka][:group]
        28:
        29:  if node[:kafka][:broker_id].nil? || node[:kafka][:broker_id].empty?
        30>>     node[:kafka][:broker_id] = node[:ipaddress].gsub(".","")
        31:  end
        32:
        33:  if node[:kafka][:broker_host_name].nil? || node[:kafka][:broker_host_name].empty?
        34:      node[:kafka][:broker_host_name] = node[:fqdn]
        35:  end
        36:
        37:  log "Broker id: #{node[:kafka][:broker_id]}"
        38:  log "Broker name: #{node[:kafka][:broker_host_name]}"
        39:


       Running handlers:

       Running handlers complete

       [2015-02-04T22:35:24+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 0 resources updated in 1.070498634 seconds
       [2015-02-04T22:35:24+00:00] ERROR: Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'
       [2015-02-04T22:35:24+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <default-ubuntu-1204>.
>>>>>> Please see .kitchen/logs/default-ubuntu-1204.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '
sudo -E /opt/chef/bin/chef-solo --config /tmp/kitchen/solo.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json
']
>>>>>> ----------------------
```

Notice how line 30 _should_ have set node[:kafka][:broker_id] to the ip address? 

Wrapper cookboook

``` bash
$cat foobar-Kafka/attributes/customize.rb
normal[:java][:jdk_version] = '7'
normal[:kafka][:version] = "0.7.0"
```

``` bash
$cat foobar-Kafka/Berksfile

source "https://supermarket.getchef.com"
metadata
cookbook 'java'
cookbook 'kafka'
```

``` bash
$tail foobar-Kafka/metadata.rb
...
depends 'apt', '~> 2.3.0'
depends 'yum', '~> 3.0.0'
depends 'java', '~> 1.29.0'
depends 'kafka', '~> 1.0.20'
```

``` yaml
$cat foobar-Kafka/.kitchen.yml

---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  # - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[ND-Kafka::default]
    attributes:
```

Then run `kitchen create`. It will fail

I'm new to chef, so I'm not sure how to work around this.

**Comment by ustuehler** [comment]
Line 30 (and 34 likewise) could be changed to:

```
node.default[:kafka][:broker_id] = node[:ipaddress].gsub(".","")
```

Could that be the fix?
